# Unordered list style
MD004:
  style: dash

# 最大行長
MD013:
  line_length: 180
  tables: false

# 不限制文档的第一个非空行标题级别
MD025:
  front_matter_title: false

# 允许标题中的尾随标点符号
MD026:
  punctuation: ".,;:!"

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Code block style
MD046:
  style: fenced
