# Unordered list style
MD004:
  style: dash

# 最大行長
MD013:
  line_length: 180
  tables: false

# 不限制文档的第一个非空行标题级别
MD025:
  front_matter_title: false

# 允许标题中的尾随任意标点
MD026:
  punctuation: ""

# Ordered list item prefix
MD029:
  style: one

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# 指定最高标题级别：1-3
MD041:
  level:
    - "1"  # 允许一级标题
    - "2"  # 允许二级标题
    - "3"  # 允许三级标题


# Code block style
MD046:
  style: fenced
